<?php

/**
 * Yii app stub file. Autogenerated by yii2-stubs-generator (stubs console command).
 * Used for enhanced IDE code autocompletion.
 * Updated on 2018-02-09T10:34:51+0800
 */
class Yii extends \yii\BaseYii
{
    /**
     * @var BaseApplication
     */
    public static $app;
}
/**
 * @property yii\rbac\DbManager $authManager
 * @property common\components\base\Formatter $formatter
 * @property \zh\cart\Cart $cart
 *
 **/
abstract class BaseApplication extends yii\base\Application
{
}

