<?php
/**
 * Copyright(c) 2018-2050,BWSC.Co.Ltd.
 * Created by PhpStorm.
 * User: JoeRowe
 * Date: 2019/12/3 0003
 * Time: 18:00
 *
 */

namespace frontend\filter;


use yii\base\ActionFilter;
use yii\web\HttpException;

class LoginFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        if (!\Yii::$app->session->has('userid') || !\Yii::$app->session->has('uid'))
        {
            throw new HttpException(403, "请先登录");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}